#!/bin/sh
g++ -c ratchblock.cpp
g++ -o ratchblock ratchblock.o

clann/clann < clann.workflow.txt

# write a file with a PAUP block that can be appended to a data matrix
sbatch runCLANN.sh
# The block generated by this command will conduct an analysis with 100 replicates
# 15% of the characters will be upweighted per replicate.
# number of characters:37158    ##### 37158 for adding babblers

#####     upweight 15,20,25,30,35
./ratchblock ratchblock_15upweight 21644 100 15 10
./ratchblock ratchblock_20upweight 21644 100 20 10
./ratchblock ratchblock_25upweight 21644 100 25 10
./ratchblock ratchblock_30upweight 21644 100 30 10
./ratchblock ratchblock_35upweight 21644 100 35 10

#### remove paup block from coding.nex
sed -n '/NEXUS/,/begin paup/p' coding.nex | head -n -1 > coding_upweight15.nex
sed -n '/NEXUS/,/begin paup/p' coding.nex | head -n -1 > coding_upweight20.nex
sed -n '/NEXUS/,/begin paup/p' coding.nex | head -n -1 > coding_upweight25.nex
sed -n '/NEXUS/,/begin paup/p' coding.nex | head -n -1 > coding_upweight30.nex
sed -n '/NEXUS/,/begin paup/p' coding.nex | head -n -1 > coding_upweight35.nex

###### cat ratchblock to coding.nex
sed '/NEXUS/d' ratchblock_15upweight.ratchblock >> coding_upweight15.nex
sed '/NEXUS/d' ratchblock_20upweight.ratchblock >> coding_upweight20.nex
sed '/NEXUS/d' ratchblock_25upweight.ratchblock >> coding_upweight25.nex
sed '/NEXUS/d' ratchblock_30upweight.ratchblock >> coding_upweight30.nex
sed '/NEXUS/d' ratchblock_35upweight.ratchblock >> coding_upweight35.nex

### run paup
### convert truncated tip labels back to species names using "convert_name_back.sh"
### remove the ' before and after the tip label
### prune tree using "remove_tips.R"
